from __future__ import annotations

MUSICBRAINZ_APP_NAME = "songbase"
MUSICBRAINZ_APP_VERSION = "0.1.0"
MUSICBRAINZ_CONTACT_EMAIL = "sycrostudios@gmail.com"

MUSICBRAINZ_RATE_LIMIT_SECONDS = 1.0
MUSICBRAINZ_MIN_SCORE = 90
MUSICBRAINZ_MAX_TAGS = 5

VERIFICATION_SOURCE = "musicbrainz"

COVER_ART_ARCHIVE_BASE_URL = "https://coverartarchive.org"
IMAGE_REQUEST_TIMEOUT_SEC = 20
IMAGE_MAX_BYTES = 10 * 1024 * 1024

IMAGE_SOURCE_COVER_ART = "cover-art-archive"
IMAGE_SOURCE_MUSICBRAINZ = "musicbrainz"

IMAGE_TYPE_COVER = "cover"
