from __future__ import annotations

MUSICBRAINZ_APP_NAME = "songbase"
MUSICBRAINZ_APP_VERSION = "0.1.0"
MUSICBRAINZ_CONTACT_EMAIL = "sycrostudios@gmail.com"

MUSICBRAINZ_RATE_LIMIT_SECONDS = 1.0
MUSICBRAINZ_MIN_SCORE = 90
MUSICBRAINZ_MAX_TAGS = 5

VERIFICATION_SOURCE = "musicbrainz"
