from __future__ import annotations

import os

MUSICBRAINZ_APP_NAME = "songbase"
MUSICBRAINZ_APP_VERSION = "0.1.0"
MUSICBRAINZ_CONTACT_EMAIL = "sycrostudios@gmail.com"

MUSICBRAINZ_RATE_LIMIT_SECONDS = 1.0
MUSICBRAINZ_MIN_SCORE = 90
MUSICBRAINZ_MAX_TAGS = 5
MUSICBRAINZ_REQUEST_RETRIES = int(os.environ.get("SONGBASE_MUSICBRAINZ_RETRIES", "2"))
MUSICBRAINZ_RETRY_BACKOFF_SEC = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_RETRY_BACKOFF_SEC", "1.0")
)
MUSICBRAINZ_RETRY_MAX_BACKOFF_SEC = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_RETRY_MAX_BACKOFF_SEC", "8.0")
)
MUSICBRAINZ_SEARCH_LIMIT = int(os.environ.get("SONGBASE_MUSICBRAINZ_SEARCH_LIMIT", "10"))
MUSICBRAINZ_MIN_TITLE_SIMILARITY = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_MIN_TITLE_SIMILARITY", "0.72")
)
MUSICBRAINZ_MIN_TITLE_SIMILARITY_NO_ARTIST = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_MIN_TITLE_SIMILARITY_NO_ARTIST", "0.85")
)
MUSICBRAINZ_MIN_ARTIST_SIMILARITY = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_MIN_ARTIST_SIMILARITY", "0.6")
)
MUSICBRAINZ_MIN_ALBUM_SIMILARITY = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_MIN_ALBUM_SIMILARITY", "0.6")
)
MUSICBRAINZ_REQUIRE_ARTIST_MATCH = os.environ.get(
    "SONGBASE_MUSICBRAINZ_REQUIRE_ARTIST_MATCH",
    "1",
).strip().lower() in {"1", "true", "yes", "on"}
MUSICBRAINZ_REQUIRE_ALBUM_MATCH = os.environ.get(
    "SONGBASE_MUSICBRAINZ_REQUIRE_ALBUM_MATCH",
    "1",
).strip().lower() in {"1", "true", "yes", "on"}
MUSICBRAINZ_DURATION_TOLERANCE_SEC = int(
    os.environ.get("SONGBASE_MUSICBRAINZ_DURATION_TOLERANCE_SEC", "5")
)
MUSICBRAINZ_DURATION_TOLERANCE_PCT = float(
    os.environ.get("SONGBASE_MUSICBRAINZ_DURATION_TOLERANCE_PCT", "0.05")
)

VERIFICATION_SOURCE = "musicbrainz"

COVER_ART_ARCHIVE_BASE_URL = "https://coverartarchive.org"
IMAGE_REQUEST_TIMEOUT_SEC = 20
IMAGE_MAX_BYTES = 10 * 1024 * 1024
IMAGE_REQUEST_RETRIES = int(os.environ.get("SONGBASE_IMAGE_REQUEST_RETRIES", "3"))
IMAGE_RETRY_BACKOFF_SEC = float(
    os.environ.get("SONGBASE_IMAGE_RETRY_BACKOFF_SEC", "1.0")
)
IMAGE_RETRY_MAX_BACKOFF_SEC = float(
    os.environ.get("SONGBASE_IMAGE_RETRY_MAX_BACKOFF_SEC", "8.0")
)

IMAGE_SOURCE_COVER_ART = "cover-art-archive"
IMAGE_SOURCE_MUSICBRAINZ = "musicbrainz"

IMAGE_TYPE_COVER = "cover"
